# Generated by Django 2.1 on 2018-08-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolo',
            name='nome',
            field=models.CharField(default='nome do bolo', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bolo',
            name='peso',
            field=models.FloatField(default=2.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bolo',
            name='preco',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bolo',
            name='sabor',
            field=models.CharField(default='baunilha', max_length=255),
            preserve_default=False,
        ),
    ]
